[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer",
    "php82Packages.mbstring",
    "php82Packages.openssl",
    "php82Packages.pdo",
    "php82Packages.pdo_sqlite",
    "php82Packages.curl",
]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views bootstrap/cache",
    "chmod -R 775 storage bootstrap/cache"
]

[phases.build]
cmds = [
    "php artisan migrate --force || echo 'Migration failed, continuing...'"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"