[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "mkdir -p storage/logs storage/framework/cache storage/framework/sessions storage/framework/views",
    "chmod -R 775 storage bootstrap/cache"
]

[phases.build]
cmds = [
    "php artisan config:clear",
    "php artisan route:clear", 
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"