[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan config:clear && php artisan serve --host=0.0.0.0 --port=$PORT"

healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production]
variables = { }